version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-client:
    build: .
    container_name: redis-client
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["python", "insert_to_redis.py"]

volumes:
  redis_data:
    driver: local
